FOOD_CATALOG = [
    {
        "name": "불고기 덮밥",
        "description": "든든한 단짠 밸런스로 점심이나 저녁에 실패 없는 한 그릇 메뉴입니다.",
        "tags": ["한식", "밥", "고기", "든든함", "집밥"],
        "moods": ["comfort", "reward", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["소고기", "양파", "간장", "밥"],
        "trend_keywords": ["직장인 점심", "집밥"],
    },
    {
        "name": "마라 크림 파스타",
        "description": "매콤함과 부드러움을 같이 챙기는 요즘형 퓨전 메뉴입니다.",
        "tags": ["양식", "면", "매운 음식", "트렌디", "크림"],
        "moods": ["reward", "adventure", "stress"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "spicy",
        "ingredients": ["파스타면", "우유", "고추기름", "베이컨"],
        "trend_keywords": ["마라", "꾸덕파스타"],
    },
    {
        "name": "연어 포케볼",
        "description": "가볍지만 단백질은 챙기고 싶은 날에 맞는 산뜻한 선택입니다.",
        "tags": ["헬시", "해산물", "샐러드", "가벼움", "다이어트"],
        "moods": ["light", "focus", "refresh"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["연어", "아보카도", "현미밥", "채소"],
        "trend_keywords": ["헬시플레이트", "포케"],
    },
    {
        "name": "김치찌개 정식",
        "description": "따뜻하고 진한 국물이 필요한 날에 가장 안정적인 선택입니다.",
        "tags": ["한식", "국물", "매운 음식", "따뜻함", "집밥"],
        "moods": ["comfort", "stress", "tired"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "spicy",
        "ingredients": ["김치", "두부", "돼지고기", "대파"],
        "trend_keywords": ["집밥", "국물요리"],
    },
    {
        "name": "계란볶음밥",
        "description": "냉장고 재료를 빠르게 활용할 수 있는 실전형 메뉴입니다.",
        "tags": ["중식", "밥", "간단요리", "가성비", "냉장고파먹기"],
        "moods": ["focus", "tired", "late"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "mild",
        "ingredients": ["계란", "밥", "대파", "햄"],
        "trend_keywords": ["초간단 레시피", "냉장고파먹기"],
    },
    {
        "name": "떡볶이 플래터",
        "description": "기분 전환이 필요할 때 확실하게 만족감을 주는 분식 조합입니다.",
        "tags": ["분식", "매운 음식", "간식", "트렌디", "스트레스해소"],
        "moods": ["reward", "stress", "fun"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "spicy",
        "ingredients": ["떡", "어묵", "고추장", "계란"],
        "trend_keywords": ["분식", "떡볶이"],
    },
    {
        "name": "닭가슴살 또띠아랩",
        "description": "바쁜 일정 사이에도 가볍게 챙기기 좋은 한 손 식사입니다.",
        "tags": ["헬시", "간편식", "단백질", "다이어트", "가벼움"],
        "moods": ["focus", "light", "refresh"],
        "meal_times": ["breakfast", "lunch"],
        "spicy": "mild",
        "ingredients": ["또띠아", "닭가슴살", "양상추", "소스"],
        "trend_keywords": ["프로틴밀", "간편식"],
    },
    {
        "name": "버섯 된장 파스타",
        "description": "익숙한 된장 풍미에 감칠맛을 더한 색다른 집밥 파스타입니다.",
        "tags": ["퓨전", "면", "집밥", "감칠맛", "따뜻함"],
        "moods": ["comfort", "adventure", "rainy"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["버섯", "된장", "파스타면", "마늘"],
        "trend_keywords": ["한식퓨전", "감칠맛"],
    },
    {
        "name": "비빔밥",
        "description": "야채와 단백질, 밥을 균형 있게 먹고 싶을 때 무난하게 좋은 한식 선택입니다.",
        "tags": ["한식", "밥", "균형식", "집밥", "야채"],
        "moods": ["comfort", "focus", "refresh"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["밥", "계란", "나물", "고추장"],
        "trend_keywords": ["집밥", "비빔밥"],
    },
    {
        "name": "제육볶음 정식",
        "description": "매콤달콤한 자극과 밥도둑 계열 만족감이 확실한 대표 점심 메뉴입니다.",
        "tags": ["한식", "밥", "고기", "매운 음식", "든든함"],
        "moods": ["reward", "stress", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "spicy",
        "ingredients": ["돼지고기", "양파", "고추장", "밥"],
        "trend_keywords": ["직장인 점심", "제육볶음"],
    },
    {
        "name": "순두부찌개",
        "description": "뜨끈하고 부드러운 국물 계열이 당길 때 편하게 고르기 좋은 메뉴입니다.",
        "tags": ["한식", "국물", "따뜻함", "집밥", "두부"],
        "moods": ["comfort", "stress", "tired"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "spicy",
        "ingredients": ["순두부", "계란", "대파", "고춧가루"],
        "trend_keywords": ["국물요리", "순두부"],
    },
    {
        "name": "된장찌개 백반",
        "description": "자극적이지 않으면서도 속을 편하게 채우는 집밥형 메뉴입니다.",
        "tags": ["한식", "국물", "집밥", "밥", "안정감"],
        "moods": ["comfort", "focus", "tired"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["된장", "두부", "애호박", "밥"],
        "trend_keywords": ["집밥", "된장찌개"],
    },
    {
        "name": "닭갈비 볶음밥 세트",
        "description": "매콤한 볶음 향과 탄수화물 만족감이 함께 오는 보상형 메뉴입니다.",
        "tags": ["한식", "밥", "매운 음식", "고기", "보상"],
        "moods": ["reward", "stress", "fun"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "spicy",
        "ingredients": ["닭고기", "양배추", "떡", "밥"],
        "trend_keywords": ["철판요리", "닭갈비"],
    },
    {
        "name": "갈비탕",
        "description": "속을 편하게 달래면서도 든든함은 놓치고 싶지 않을 때 잘 맞습니다.",
        "tags": ["한식", "국물", "고기", "든든함", "따뜻함"],
        "moods": ["comfort", "tired", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["소갈비", "무", "대파", "당면"],
        "trend_keywords": ["보양식", "국물요리"],
    },
    {
        "name": "돼지국밥",
        "description": "한 그릇으로 확실하게 배를 채우고 싶을 때 만족도가 높은 국밥 메뉴입니다.",
        "tags": ["한식", "국물", "밥", "든든함", "가성비"],
        "moods": ["comfort", "focus", "tired"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "mild",
        "ingredients": ["돼지고기", "국수", "대파", "쌀"],
        "trend_keywords": ["국밥", "든든한한끼"],
    },
    {
        "name": "칼국수",
        "description": "비 오거나 쌀쌀한 날 부드럽고 편한 면 요리가 필요할 때 적합합니다.",
        "tags": ["한식", "면", "국물", "따뜻함", "집밥"],
        "moods": ["comfort", "rainy", "tired"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["칼국수면", "애호박", "감자", "국물"],
        "trend_keywords": ["면요리", "따뜻한국물"],
    },
    {
        "name": "냉모밀 세트",
        "description": "무겁지 않게 시원하고 깔끔하게 먹고 싶은 날에 어울립니다.",
        "tags": ["일식", "면", "가벼움", "시원함", "깔끔함"],
        "moods": ["refresh", "light", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["메밀면", "쯔유", "무", "김"],
        "trend_keywords": ["여름메뉴", "냉모밀"],
    },
    {
        "name": "가츠동",
        "description": "짭짤한 소스와 튀김 만족감으로 확실하게 힘을 내고 싶을 때 좋은 메뉴입니다.",
        "tags": ["일식", "밥", "고기", "든든함", "보상"],
        "moods": ["reward", "focus", "comfort"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["돈가스", "양파", "계란", "밥"],
        "trend_keywords": ["덮밥", "돈가스"],
    },
    {
        "name": "부타동",
        "description": "달큰한 간장 풍미와 고기 볼륨으로 만족도가 높은 일본식 덮밥입니다.",
        "tags": ["일식", "밥", "고기", "단짠", "든든함"],
        "moods": ["reward", "focus", "comfort"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["돼지고기", "양파", "간장", "밥"],
        "trend_keywords": ["덮밥", "일식한그릇"],
    },
    {
        "name": "사케동",
        "description": "기름진 연어와 밥 조합을 산뜻하게 즐기고 싶을 때 잘 맞는 메뉴입니다.",
        "tags": ["일식", "밥", "해산물", "가벼움", "프리미엄"],
        "moods": ["refresh", "reward", "light"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["연어", "밥", "간장", "와사비"],
        "trend_keywords": ["연어덮밥", "사케동"],
    },
    {
        "name": "돈코츠 라멘",
        "description": "진한 국물과 면발로 확실하게 기분 전환하고 싶을 때 좋은 선택입니다.",
        "tags": ["일식", "면", "국물", "든든함", "야식"],
        "moods": ["reward", "stress", "late"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "mild",
        "ingredients": ["라멘면", "차슈", "계란", "육수"],
        "trend_keywords": ["라멘", "국물면"],
    },
    {
        "name": "탄탄멘",
        "description": "고소함과 얼얼한 매운맛을 동시에 원할 때 잘 맞는 면 요리입니다.",
        "tags": ["중식", "면", "매운 음식", "고소함", "자극적"],
        "moods": ["stress", "reward", "focus"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "spicy",
        "ingredients": ["면", "다진고기", "청경채", "땅콩소스"],
        "trend_keywords": ["탄탄멘", "매운면"],
    },
    {
        "name": "마파두부 덮밥",
        "description": "맵고 진한 소스 덕분에 밥이 잘 넘어가는 중식 한 그릇 메뉴입니다.",
        "tags": ["중식", "밥", "매운 음식", "두부", "든든함"],
        "moods": ["stress", "reward", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "spicy",
        "ingredients": ["두부", "다진고기", "고추기름", "밥"],
        "trend_keywords": ["마파두부", "중식덮밥"],
    },
    {
        "name": "유린기 라이스",
        "description": "바삭한 튀김과 상큼한 소스 조합이 땡길 때 좋은 보상형 메뉴입니다.",
        "tags": ["중식", "밥", "고기", "바삭함", "보상"],
        "moods": ["reward", "fun", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["닭고기", "양파", "간장소스", "밥"],
        "trend_keywords": ["중화요리", "유린기"],
    },
    {
        "name": "팟타이",
        "description": "달콤짭짤한 소스와 면의 균형이 좋아 부담 없이 즐기기 좋은 메뉴입니다.",
        "tags": ["동남아", "면", "새콤달콤", "트렌디", "가벼움"],
        "moods": ["refresh", "light", "adventure"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["쌀국수면", "숙주", "새우", "땅콩"],
        "trend_keywords": ["태국요리", "팟타이"],
    },
    {
        "name": "쌀국수",
        "description": "맑고 향긋한 국물로 속 부담 없이 먹기 좋은 안정적인 선택입니다.",
        "tags": ["동남아", "면", "국물", "가벼움", "따뜻함"],
        "moods": ["comfort", "refresh", "light"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["쌀국수면", "숙주", "양파", "육수"],
        "trend_keywords": ["베트남음식", "쌀국수"],
    },
    {
        "name": "반미 샌드위치",
        "description": "빵과 고기, 채소를 빠르게 챙기고 싶을 때 좋은 가벼운 식사입니다.",
        "tags": ["동남아", "샌드위치", "간편식", "가벼움", "이동식"],
        "moods": ["focus", "refresh", "light"],
        "meal_times": ["breakfast", "lunch"],
        "spicy": "mild",
        "ingredients": ["바게트", "고기", "오이", "당근"],
        "trend_keywords": ["샌드위치", "반미"],
    },
    {
        "name": "치킨 시저 샐러드",
        "description": "과하게 무겁지 않게 단백질과 포만감을 챙기고 싶을 때 적합합니다.",
        "tags": ["샐러드", "헬시", "단백질", "가벼움", "다이어트"],
        "moods": ["light", "focus", "refresh"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["닭가슴살", "로메인", "치즈", "드레싱"],
        "trend_keywords": ["헬시플레이트", "샐러드"],
    },
    {
        "name": "그릴드 치킨 현미볼",
        "description": "균형 잡힌 탄단지 조합으로 깔끔하게 먹고 싶은 날에 잘 맞습니다.",
        "tags": ["헬시", "밥", "단백질", "가벼움", "균형식"],
        "moods": ["focus", "light", "refresh"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["닭고기", "현미밥", "브로콜리", "옥수수"],
        "trend_keywords": ["프로틴밀", "헬시플레이트"],
    },
    {
        "name": "아보카도 오픈 토스트",
        "description": "가볍지만 분위기 있게 아침이나 브런치를 챙기고 싶을 때 좋습니다.",
        "tags": ["브런치", "빵", "가벼움", "헬시", "카페무드"],
        "moods": ["refresh", "light", "aesthetic"],
        "meal_times": ["breakfast", "lunch"],
        "spicy": "mild",
        "ingredients": ["식빵", "아보카도", "계란", "치즈"],
        "trend_keywords": ["브런치", "오픈토스트"],
    },
    {
        "name": "프렌치 토스트 플레이트",
        "description": "달콤하고 편안한 분위기의 아침 메뉴를 원할 때 만족도가 높습니다.",
        "tags": ["브런치", "빵", "달콤함", "편안함", "카페무드"],
        "moods": ["comfort", "light", "reward"],
        "meal_times": ["breakfast", "lunch"],
        "spicy": "mild",
        "ingredients": ["식빵", "계란", "우유", "버터"],
        "trend_keywords": ["브런치", "프렌치토스트"],
    },
    {
        "name": "잠봉뵈르 샌드위치",
        "description": "짭짤한 햄과 버터 풍미로 간단하지만 만족감 있는 브런치 메뉴입니다.",
        "tags": ["브런치", "샌드위치", "간편식", "고소함", "카페무드"],
        "moods": ["focus", "light", "reward"],
        "meal_times": ["breakfast", "lunch"],
        "spicy": "mild",
        "ingredients": ["바게트", "햄", "버터", "치즈"],
        "trend_keywords": ["샌드위치", "카페브런치"],
    },
    {
        "name": "치즈버거 세트",
        "description": "복잡하게 고민하기 싫고 확실한 만족감을 원할 때 가장 직관적인 선택입니다.",
        "tags": ["패스트푸드", "빵", "고기", "보상", "든든함"],
        "moods": ["reward", "stress", "fun"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "mild",
        "ingredients": ["번", "패티", "치즈", "양상추"],
        "trend_keywords": ["햄버거", "치즈버거"],
    },
    {
        "name": "페퍼로니 피자",
        "description": "여럿이 먹거나 기분 좋게 탄수화물 만족을 챙기고 싶을 때 좋습니다.",
        "tags": ["양식", "빵", "치즈", "보상", "파티"],
        "moods": ["reward", "fun", "late"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "mild",
        "ingredients": ["도우", "치즈", "토마토소스", "페퍼로니"],
        "trend_keywords": ["피자", "야식메뉴"],
    },
    {
        "name": "봉골레 파스타",
        "description": "무겁지 않으면서 감칠맛 있는 면 요리를 먹고 싶을 때 잘 맞습니다.",
        "tags": ["양식", "면", "해산물", "깔끔함", "감칠맛"],
        "moods": ["refresh", "focus", "light"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["파스타면", "조개", "마늘", "올리브오일"],
        "trend_keywords": ["오일파스타", "봉골레"],
    },
    {
        "name": "라자냐",
        "description": "치즈와 토마토소스로 깊은 만족감을 주는 오븐형 보상 메뉴입니다.",
        "tags": ["양식", "치즈", "고기", "보상", "든든함"],
        "moods": ["reward", "comfort", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["라자냐면", "치즈", "다진고기", "토마토소스"],
        "trend_keywords": ["오븐요리", "라자냐"],
    },
    {
        "name": "트러플 크림 리소토",
        "description": "부드럽고 진한 풍미로 기분 좋게 스스로를 챙기고 싶은 날에 어울립니다.",
        "tags": ["양식", "밥", "크림", "고급스러움", "보상"],
        "moods": ["reward", "comfort", "aesthetic"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["쌀", "버섯", "치즈", "크림"],
        "trend_keywords": ["리소토", "트러플"],
    },
    {
        "name": "오므라이스",
        "description": "부드러운 계란과 볶음밥 조합으로 남녀노소 편하게 먹기 좋은 메뉴입니다.",
        "tags": ["양식", "밥", "계란", "부드러움", "집밥"],
        "moods": ["comfort", "light", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["계란", "밥", "케첩", "양파"],
        "trend_keywords": ["계란요리", "오므라이스"],
    },
    {
        "name": "크림 새우 우동",
        "description": "부드러운 소스와 통통한 새우가 어우러져 색다른 만족감을 주는 면 요리입니다.",
        "tags": ["퓨전", "면", "해산물", "크림", "보상"],
        "moods": ["reward", "adventure", "comfort"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["우동면", "새우", "우유", "양파"],
        "trend_keywords": ["퓨전면", "크림우동"],
    },
    {
        "name": "김밥 + 라면 세트",
        "description": "간단하지만 실패 없는 조합으로 혼밥이나 야식에 잘 맞는 메뉴입니다.",
        "tags": ["분식", "면", "밥", "간편식", "야식"],
        "moods": ["comfort", "late", "fun"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "mild",
        "ingredients": ["김밥", "라면", "단무지", "계란"],
        "trend_keywords": ["분식", "야식메뉴"],
    },
    {
        "name": "로제 떡볶이",
        "description": "매콤함과 꾸덕함을 함께 즐기고 싶을 때 강하게 만족감을 주는 메뉴입니다.",
        "tags": ["분식", "매운 음식", "크림", "트렌디", "보상"],
        "moods": ["reward", "stress", "fun"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "spicy",
        "ingredients": ["떡", "소시지", "우유", "고추장"],
        "trend_keywords": ["로제", "떡볶이"],
    },
    {
        "name": "참치마요 주먹밥",
        "description": "빠르게 한 끼를 해결하면서도 익숙한 맛을 원할 때 좋은 간편 메뉴입니다.",
        "tags": ["간편식", "밥", "가성비", "이동식", "간단요리"],
        "moods": ["focus", "tired", "light"],
        "meal_times": ["breakfast", "lunch", "late-night"],
        "spicy": "mild",
        "ingredients": ["밥", "참치", "마요네즈", "김"],
        "trend_keywords": ["간단요리", "주먹밥"],
    },
    {
        "name": "에그마요 샌드위치",
        "description": "아침이나 이동 중에도 부담 없이 먹기 좋은 부드러운 샌드위치입니다.",
        "tags": ["간편식", "샌드위치", "계란", "부드러움", "가벼움"],
        "moods": ["light", "focus", "comfort"],
        "meal_times": ["breakfast", "lunch"],
        "spicy": "mild",
        "ingredients": ["식빵", "계란", "마요네즈", "상추"],
        "trend_keywords": ["샌드위치", "에그마요"],
    },
    {
        "name": "닭죽",
        "description": "속이 편하고 자극 없는 메뉴가 필요할 때 가장 안정적으로 고를 수 있습니다.",
        "tags": ["한식", "죽", "부드러움", "따뜻함", "회복식"],
        "moods": ["comfort", "tired", "light"],
        "meal_times": ["breakfast", "lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["쌀", "닭고기", "대파", "참기름"],
        "trend_keywords": ["회복식", "죽"],
    },
    {
        "name": "베이컨 크림 수프 파스타",
        "description": "꾸덕하고 포근한 맛으로 하루를 달래고 싶을 때 잘 맞는 크림 면 요리입니다.",
        "tags": ["양식", "면", "크림", "따뜻함", "보상"],
        "moods": ["comfort", "reward", "rainy"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["파스타면", "베이컨", "우유", "마늘"],
        "trend_keywords": ["꾸덕파스타", "크림파스타"],
    },
]

FASHION_CATALOG = [
    {
        "name": "미니멀 셋업 룩",
        "description": "정돈된 실루엣으로 출근과 약속을 모두 커버하는 데일리 코디입니다.",
        "styles": ["미니멀", "포멀"],
        "colors": ["블랙", "네이비", "그레이", "화이트"],
        "personal_colors": ["winter cool", "summer cool"],
        "temp_min": 10,
        "temp_max": 22,
        "conditions": ["clear", "cloudy"],
        "trend_keywords": ["셋업", "미니멀룩"],
    },
    {
        "name": "크림 니트 레이어드",
        "description": "부드러운 톤으로 차분하고 포근한 인상을 주는 조합입니다.",
        "styles": ["미니멀", "캐주얼"],
        "colors": ["크림", "베이지", "아이보리"],
        "personal_colors": ["spring warm", "autumn warm"],
        "temp_min": 5,
        "temp_max": 18,
        "conditions": ["clear", "cloudy", "windy"],
        "trend_keywords": ["니트레이어드", "톤온톤"],
    },
    {
        "name": "스트릿 윈드브레이커",
        "description": "활동량이 많고 가볍게 포인트를 주고 싶은 날에 적합합니다.",
        "styles": ["스트릿", "스포티"],
        "colors": ["카키", "블랙", "네온", "블루"],
        "personal_colors": ["spring warm", "winter cool"],
        "temp_min": 12,
        "temp_max": 24,
        "conditions": ["windy", "cloudy", "clear"],
        "trend_keywords": ["고프코어", "윈드브레이커"],
    },
    {
        "name": "모노톤 데님 믹스",
        "description": "캐주얼하지만 단정해 보여서 캠퍼스와 카페 일정에 잘 어울립니다.",
        "styles": ["캐주얼", "미니멀"],
        "colors": ["블루", "화이트", "그레이"],
        "personal_colors": ["summer cool", "winter cool"],
        "temp_min": 14,
        "temp_max": 26,
        "conditions": ["clear", "cloudy"],
        "trend_keywords": ["데님룩", "클린핏"],
    },
    {
        "name": "코지 라운지웨어",
        "description": "집중해서 일하거나 집에서 쉬는 날 편안함을 우선하는 선택입니다.",
        "styles": ["캐주얼", "홈웨어"],
        "colors": ["그레이", "크림", "핑크", "민트"],
        "personal_colors": ["spring warm", "summer cool"],
        "temp_min": 18,
        "temp_max": 30,
        "conditions": ["rainy", "cloudy", "clear"],
        "trend_keywords": ["꾸안꾸", "라운지웨어"],
    },
    {
        "name": "포멀 블레이저 포인트",
        "description": "프레젠테이션이나 중요한 일정에 신뢰감을 주는 조합입니다.",
        "styles": ["포멀", "미니멀"],
        "colors": ["네이비", "블랙", "와인", "화이트"],
        "personal_colors": ["winter cool", "autumn warm"],
        "temp_min": 8,
        "temp_max": 22,
        "conditions": ["clear", "cloudy"],
        "trend_keywords": ["블레이저룩", "오피스코어"],
    },
    {
        "name": "애슬레저 트레이닝 셋",
        "description": "가볍게 몸을 움직이거나 이동이 많은 날에 적합한 실전형 코디입니다.",
        "styles": ["스포티", "캐주얼"],
        "colors": ["블랙", "차콜", "블루", "화이트"],
        "personal_colors": ["summer cool", "winter cool"],
        "temp_min": 15,
        "temp_max": 28,
        "conditions": ["clear", "cloudy", "windy"],
        "trend_keywords": ["애슬레저", "러닝룩"],
    },
]

CONTENT_CATALOG = [
    {
        "name": "한 회 완결형 힐링 웹툰",
        "description": "짧은 시간 안에 기분 전환이 가능한 가벼운 웹툰 타입입니다.",
        "genres": ["로맨스", "일상", "힐링"],
        "platforms": ["웹툰"],
        "moods": ["light", "comfort", "refresh"],
        "trend_keywords": ["힐링웹툰", "짧은콘텐츠"],
    },
    {
        "name": "몰입형 범죄 스릴러 영화",
        "description": "한 번에 몰입해서 보고 싶은 저녁 시간에 잘 맞는 선택입니다.",
        "genres": ["스릴러", "범죄", "미스터리"],
        "platforms": ["영화"],
        "moods": ["focus", "dark", "reward"],
        "trend_keywords": ["범죄스릴러", "반전영화"],
    },
    {
        "name": "20분 생산성 유튜브",
        "description": "의욕을 끌어올리고 싶을 때 짧게 보기 좋은 자기계발형 콘텐츠입니다.",
        "genres": ["자기계발", "브이로그", "정보"],
        "platforms": ["유튜브"],
        "moods": ["focus", "refresh", "light"],
        "trend_keywords": ["생산성", "루틴영상"],
    },
    {
        "name": "감성 로맨틱 코미디 드라마",
        "description": "하루를 부드럽게 마무리하고 싶을 때 안정적으로 즐길 수 있습니다.",
        "genres": ["로맨스", "코미디", "드라마"],
        "platforms": ["드라마"],
        "moods": ["comfort", "light", "reward"],
        "trend_keywords": ["로코", "감성드라마"],
    },
    {
        "name": "판타지 세계관 웹툰",
        "description": "현실 분리가 필요할 때 몰입감을 주는 장르형 선택입니다.",
        "genres": ["판타지", "액션", "모험"],
        "platforms": ["웹툰"],
        "moods": ["adventure", "reward", "focus"],
        "trend_keywords": ["이세계", "판타지웹툰"],
    },
    {
        "name": "현장감 있는 여행 브이로그",
        "description": "밖에 나가기 어렵더라도 간접 여행 기분을 낼 수 있는 콘텐츠입니다.",
        "genres": ["여행", "브이로그", "힐링"],
        "platforms": ["유튜브"],
        "moods": ["refresh", "light", "comfort"],
        "trend_keywords": ["여행브이로그", "로컬맛집"],
    },
    {
        "name": "짧고 강한 SF 미드",
        "description": "빠르게 다음 화를 누르게 만드는 텐션 높은 선택지입니다.",
        "genres": ["SF", "스릴러", "드라마"],
        "platforms": ["드라마"],
        "moods": ["focus", "dark", "adventure"],
        "trend_keywords": ["SF드라마", "떡밥회수"],
    },
    {
        "name": "마음 편한 요리 영화",
        "description": "먹고 싶은 기분과 따뜻한 분위기를 동시에 채워주는 타입입니다.",
        "genres": ["드라마", "힐링", "음식"],
        "platforms": ["영화"],
        "moods": ["comfort", "light", "foodie"],
        "trend_keywords": ["푸드필름", "힐링무비"],
    },
]

ACTIVITY_CATALOG = [
    {
        "name": "카페 저널링",
        "description": "혼자서도 집중감 있게 하루를 정리할 수 있는 저자극 활동입니다.",
        "indoor_outdoor": "indoor",
        "energy": "low",
        "social": "solo",
        "budget": "medium",
        "trend_keywords": ["감성카페", "기록습관"],
    },
    {
        "name": "한강 산책 루프",
        "description": "가볍게 몸을 움직이며 머리를 환기시키기 좋은 대표적인 리셋 활동입니다.",
        "indoor_outdoor": "outdoor",
        "energy": "medium",
        "social": "either",
        "budget": "low",
        "trend_keywords": ["산책", "러닝크루"],
    },
    {
        "name": "집중형 보드게임 나이트",
        "description": "친구와 함께 실내에서 텐션 있게 시간을 보내기 좋은 선택입니다.",
        "indoor_outdoor": "indoor",
        "energy": "medium",
        "social": "group",
        "budget": "medium",
        "trend_keywords": ["보드게임", "집모임"],
    },
    {
        "name": "실내 클라이밍 체험",
        "description": "몸을 쓰면서도 성취감을 빠르게 느낄 수 있는 액티브한 활동입니다.",
        "indoor_outdoor": "indoor",
        "energy": "high",
        "social": "either",
        "budget": "medium",
        "trend_keywords": ["클라이밍", "액티비티"],
    },
    {
        "name": "동네 전시 산책",
        "description": "실내외를 오가며 새로운 자극을 얻고 싶은 날에 어울립니다.",
        "indoor_outdoor": "mixed",
        "energy": "medium",
        "social": "either",
        "budget": "medium",
        "trend_keywords": ["전시회", "문화생활"],
    },
    {
        "name": "홈트 20분 챌린지",
        "description": "시간이 많지 않아도 컨디션을 끌어올릴 수 있는 짧은 루틴입니다.",
        "indoor_outdoor": "indoor",
        "energy": "high",
        "social": "solo",
        "budget": "low",
        "trend_keywords": ["홈트", "짧은운동"],
    },
    {
        "name": "친구와 신상 맛집 탐방",
        "description": "주말이나 퇴근 후에 대화와 먹는 즐거움을 함께 챙길 수 있습니다.",
        "indoor_outdoor": "outdoor",
        "energy": "medium",
        "social": "group",
        "budget": "high",
        "trend_keywords": ["신상맛집", "핫플"],
    },
    {
        "name": "방 정리 + 플레이리스트 업데이트",
        "description": "적은 예산으로 분위기를 전환하고 성취감도 남기는 실내 활동입니다.",
        "indoor_outdoor": "indoor",
        "energy": "low",
        "social": "solo",
        "budget": "low",
        "trend_keywords": ["방꾸미기", "플리추천"],
    },
]
